export { default as ChatPage } from "./Chat";
export { default as Feed } from "./Feed";
export { default as Home } from "./Home";
export { default as Profile } from "./Profile";
export { default as Settings } from "./Settings";
export { default as GroupDetails } from "./GroupDetails";
export { default as JoinGroup } from "./JoinGroup";
export { default as Explore } from "./Explore";
export { default as Friends } from "./Friends";
